name: thesis_lints_example
publish_to: none

environment:
  sdk: ^3.5.3

dev_dependencies:
  custom_lint: ^0.7.0
  thesis_lints:
    path: ../

dependencies:
  archive: ^3.6.1
  crypto: ^3.0.5
  encrypt: ^5.0.3
  http: ^1.2.2
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  web_socket_channel: ^3.0.1
  webview_flutter: ^4.10.0
